USE [GD1C2025]
GO

DELETE FROM MAUV.Sucursal
DELETE FROM MAUV.Pedido
DELETE FROM MAUV.Cliente
DELETE FROM MAUV.Factura
DELETE FROM MAUV.Detalle_Factura
DELETE FROM MAUV.Sillon
DELETE FROM MAUV.Envio
DELETE FROM MAUV.Cancelacion_Pedido
DELETE FROM MAUV.Compra
DELETE FROM MAUV.Detalle_Compra
DELETE FROM MAUV.Proveedor
DELETE FROM MAUV.Detalle_Pedido
DELETE FROM MAUV.Sillon_Medida
DELETE FROM MAUV.SillonXMaterial
DELETE FROM MAUV.Sillon_Modelo
DELETE FROM MAUV.Tela
DELETE FROM MAUV.Madera
DELETE FROM MAUV.Relleno
DELETE FROM MAUV.Material
go

DROP FROM MAUV.Sucursal
DROP FROM MAUV.Pedido
DROP FROM MAUV.Cliente
DROP FROM MAUV.Factura
DROP FROM MAUV.Detalle_Factura
DROP FROM MAUV.Sillon
DROP FROM MAUV.Envio
DROP FROM MAUV.Cancelacion_Pedido
DROP FROM MAUV.Compra
DROP FROM MAUV.Detalle_Compra
DROP FROM MAUV.Proveedor
DROP FROM MAUV.Detalle_Pedido
DROP FROM MAUV.Sillon_Medida
DROP FROM MAUV.SillonXMaterial
DROP FROM MAUV.Sillon_Modelo
DROP FROM MAUV.Tela
DROP FROM MAUV.Madera
DROP FROM MAUV.Relleno
DROP FROM MAUV.Material
go

DROP SCHEMA MAUV
GO
